[package]
name = "fast_math"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
f256 = "0.1.2"
#fixed = "1.23.1"

[dev-dependencies]
rand = "0.8.5"

[profile.test]
opt-level = 3

[profile.release]
opt-level = 3
panic = "abort"

