[package]
name = "fath"
authors = [ "burgerindividual", "duplexsystem" ]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/burgerindividual/fath"
description = "Fa(st ma)th library built for speed."

[dev-dependencies]
rand = "0.8.5"

[profile.test]
opt-level = 3

[profile.release]
opt-level = 3
panic = "abort"
